apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: reports-server-test-v3
  region: us-west-1
nodeGroups:
  - name: ng-1
    instanceType: t3a.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 20
    iam:
      withAddonPolicies:
        autoScaler: true
        ebs: true
        cloudWatch: true
