apiVersion: v1
kind: Pod
metadata:
  name: compliant-pod
  namespace: test-policies
  labels:
    app: test
    version: v1
spec:
  containers:
  - name: nginx
    image: nginx:latest
    securityContext:
      privileged: false
      runAsNonRoot: true
      runAsUser: 1000
    ports:
    - containerPort: 80
