apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: reports-server
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reports-server
  endpoints:
  - port: https
    interval: 30s
    path: /metrics
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - kyverno
